name: CloudHub 2.0 deployment workflow

on:
  push:
    branches: [ "main", "dev", "test" ]
  pull_request:
    branches: [ "main", "dev", "test" ]

jobs:
  deployToDev:
    if: ${{ github.ref == 'refs/heads/dev' }} 
    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENT_ID: ${{ secrets.CONNECTEDAPP_CLIENT_ID }}
      CONNECTEDAPP_CLIENT_SECRET: ${{ secrets.CONNECTEDAPP_CLIENT_SECRET }}    
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Updating POM Version   
      run: |
        git config user.email "email ID"
        git config user.name "Username"
        git config pull.rebase false
        git checkout dev
        mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit -s settings.xml --file pom.xml
        git add pom.xml
        git commit -m "[skip ci] version updated."
        git push origin dev  
        
    - name: Publish to Exchange    
      run: mvn deploy --file pom.xml -s settings.xml  
      
    - name: Deploy to CH2 dev    
      run: mvn deploy -DmuleDeploy -Dmule.env=dev --file pom.xml -s settings.xml   
      

  deployToTest:
    if: ${{ github.ref == 'refs/heads/test' }}
    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENT_ID: ${{ secrets.CONNECTEDAPP_CLIENT_ID }}
      CONNECTEDAPP_CLIENT_SECRET: ${{ secrets.CONNECTEDAPP_CLIENT_SECRET }}    
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven        
   
    - name: Deploy to CH2 test  
      run: mvn deploy -DmuleDeploy -Dmule.env=test --file pom.xml -s settings.xml 


  deployToProd:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENT_ID: ${{ secrets.CONNECTEDAPP_CLIENT_ID }}
      CONNECTEDAPP_CLIENT_SECRET: ${{ secrets.CONNECTEDAPP_CLIENT_SECRET }}    
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven        
      
    - name: Deploy to CH2 prod     
      run: mvn deploy -DmuleDeploy -Dmule.env=prod --file pom.xml -s settings.xml 


